# Generated by Django 4.1.1 on 2023-10-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptionImageModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromName', models.CharField(max_length=100)),
                ('toName', models.CharField(max_length=100)),
                ('secretKey', models.CharField(max_length=100)),
                ('path1', models.CharField(max_length=100)),
                ('path2', models.CharField(max_length=100)),
                ('cdate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'EncryptionImage',
            },
        ),
    ]
